### ISSUE TITLE
404 page on Android

### ISSUE THREAD

**Issue by alzhab** [WalletConnect/walletconnect-monorepo#1060] opened 2022-05-21 09:43 UTC
**Describe the bug**
Hi! I'm using react native with wallet connect
connect method dont't open metamask app on playmarket, only 404 Error on website

**Screenshots**
![photo_2022-05-21_15-41-33](https://user-images.githubusercontent.com/47349292/169645832-6d0af4a6-cdf3-456d-bcfd-2dd8a87ac5b8.jpg)

**Comment by Dzhakhar** [comment] 2022-06-06 06:30
Hi, did you find any solution? Facing same issue

**Comment by ChJ4m35** [comment] 2022-06-09 11:21
Same

**Comment by Dzhakhar** [comment] 2022-06-11 15:28
@ChJ4m3s I found a solution. No webview needed. Can share it if anyone still needs

**Comment by ChJ4m35** [comment] 2022-06-11 15:46
yes, could be interesting :)

**Comment by ghorbani-m** [comment] 2022-06-11 16:08
Same issue.
"react-native": "0.66.3",
"@walletconnect/react-native-dapp": "^1.7.8",

**Comment by Dzhakhar** [comment] 2022-06-11 18:36
The reason is that walletconnect is trying to ask Android device if it can open wc uri or no, new android SDK by default says NO to all URI schemes that are not registered in AndroidManifest.xml.

So edit your android/app/src/main/AndroidManifest.xml and add the following code:

```
<queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="wc"/>
        </intent>
    </queries>
```

Rebuild your project, the error should disappear. If it won't solve the problem, let me know

**Comment by ghorbani-m** [comment] 2022-06-12 08:52
> The reason is that walletconnect is trying to ask Android device if it can open wc uri or no, new android SDK by default says NO to all URI schemes that are not registered in AndroidManifest.xml.
> 
> So edit your android/app/src/main/AndroidManifest.xml and add the following code:
> 
> ```
> <queries>
>         <intent>
>             <action android:name="android.intent.action.VIEW" />
>             <data android:scheme="wc"/>
>         </intent>
>     </queries>
> ```
> 
> Rebuild your project, the error should disappear. If it won't solve the problem, let me know

Thank you, it works

**Comment by ChJ4m35** [comment] 2022-06-12 09:43
Yes, I confirm too! Thanks a lot

**Comment by mcuelenaere** [comment] 2022-06-20 10:11
I believe this is a duplicate of https://github.com/WalletConnect/walletconnect-monorepo/issues/840

**Comment by SavelevaOnClick** [comment] 2022-08-20 14:45
> <queries>
>         <intent>
>             <action android:name="android.intent.action.VIEW" />
>             <data android:scheme="wc"/>
>         </intent>
>     </queries>


maybe I'm doing something wrong, but the same 404

**Comment by nhatnguyen95** [comment] 2022-09-15 06:53
we should install at least one wallet like Meta mask, Trust wallet,...

**Comment by unaigl** [comment] 2022-09-23 11:59
> The reason is that walletconnect is trying to ask Android device if it can open wc uri or no, new android SDK by default says NO to all URI schemes that are not registered in AndroidManifest.xml.
> 
> So edit your android/app/src/main/AndroidManifest.xml and add the following code:
> 
> ```
> <queries>
>         <intent>
>             <action android:name="android.intent.action.VIEW" />
>             <data android:scheme="wc"/>
>         </intent>
>     </queries>
> ```
> 
> Rebuild your project, the error should disappear. If it won't solve the problem, let me know

Hi guys, I'm new to react native, as I read this works when ejecting? Is there any way to handle it in development?

**Comment by unaigl** [comment] 2022-09-23 15:50
> > The reason is that walletconnect is trying to ask Android device if it can open wc uri or no, new android SDK by default says NO to all URI schemes that are not registered in AndroidManifest.xml.
> > So edit your android/app/src/main/AndroidManifest.xml and add the following code:
> > ```
> > <queries>
> >         <intent>
> >             <action android:name="android.intent.action.VIEW" />
> >             <data android:scheme="wc"/>
> >         </intent>
> >     </queries>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Rebuild your project, the error should disappear. If it won't solve the problem, let me know
> 
> Thank you, it works

Hi guys, I'm new to react native. Is there any way to handle it in development using expo?

**Comment by Lauman** [comment] 2022-10-24 15:21
> The reason is that walletconnect is trying to ask Android device if it can open wc uri or no, new android SDK by default says NO to all URI schemes that are not registered in AndroidManifest.xml.
> 
> So edit your android/app/src/main/AndroidManifest.xml and add the following code:
> 
> ```
> <queries>
>         <intent>
>             <action android:name="android.intent.action.VIEW" />
>             <data android:scheme="wc"/>
>         </intent>
>     </queries>
> ```
> 
> Rebuild your project, the error should disappear. If it won't solve the problem, let me know

In Android 11 works but in Android 7 no.
Can it be configured to redirect to another page?
Thanks.

**Comment by kashishkhullar** [comment] 2022-12-01 22:56
@Dzhakhar How do I resolve this if I am using Expo?

**Comment by ChJ4m35** [comment] 2022-12-01 22:58
You have to eject Expo: https://docs.expo.dev/workflow/customizing/

**Comment by finessevanes** [comment] 2023-02-16 09:57
Is this still an issue?

**Comment by ChJ4m35** [comment] 2023-02-16 10:11
It is not, the solution proposed by Lauman worked for me.

**Closed as completed** 2023-02-16 10:20 UTC
Labels: type: bug, status: needs information
