### ISSUE TITLE
there's no response of 'irn_unsubscribe' from 'wss://relay.walletconnect.com'

### ISSUE THREAD

**Issue by hangole1999** [WalletConnect/walletconnect-monorepo#2703] opened 2023-06-21 08:17 UTC
**Describe the bug**
request the `irn_unsubscribe` method of `wss` in the [DOCS](https://docs.walletconnect.com/2.0/specs/servers/relay/relay-server-rpc#unsubscribe-payload), i should get a response, but it is said that `request is not finished yet` and the request did not end.

**SDK Version (if relevant)**
 - Client: JS (Next + React + TS)
 - Version: `@walletconnect/ethereum-provider@2.8.1`, `@walletconnect/modal@2.4.7`

**To Reproduce**
```
const walletconnectOption = {
  projectId: "...",
  chains: [...],
  methods: [
    "eth_sendTransaction",
    "eth_signTransaction",
    "eth_sign",
    "personal_sign",
    "eth_signTypedData",
  ],
  events: ["chainChanged", "accountsChanged"],
  rpcMap: {
    "...": "...",
    ...
  },
  showQrModal: true,
};
const { EthereumProvider } = await import("@walletconnect/ethereum-provider");
const etherProvider = await EthereumProvider.init(walletconnectOption);
await etherProvider.connect(walletconnectOption);
```

**Expected behavior**
The user cannot open the modal of the walletconnect and cannot use it.

**Screenshots**
![Screen Shot 2023-06-21 at 17 27 56](https://github.com/WalletConnect/walletconnect-monorepo/assets/16486381/6912c215-2cbe-44a0-804e-5a1eb75b4d37)
![Screen Shot 2023-06-21 at 17 28 10](https://github.com/WalletConnect/walletconnect-monorepo/assets/16486381/2db138af-c604-4ab0-916f-5d7a251c6683)
![Screen Shot 2023-06-21 at 17 28 13](https://github.com/WalletConnect/walletconnect-monorepo/assets/16486381/e563810e-e4ec-4898-802b-d14e73f78a83)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.7.7
 - Browser: Chrome
 - Version: Chrome 114.0.5735.106 (Official Build) (x86_64)

**Additional context**
What can i do ?

**Comment by Jlp18** [comment] 2023-06-21 09:29
@hangole1999 When is it expected to be resolved?

**Comment by boidushya** [comment] 2023-06-21 12:24
Duplicate of #2700 

Further clarity: [Partial Relay Outage in the Southeast Asia Region](https://status.walletconnect.com/incidents/r57h5rplk20t)

Closing this issue, since this should be resolved and behaviours should be back to normal.

**Closed as not planned by boidushya** 2023-06-21 12:24 UTC
Labels: type: bug
