### ISSUE TITLE
Inconsistency in disconnection event WC V2 -  Relayer network

### ISSUE THREAD

**Issue by leapsamvel** [WalletConnect/walletconnect-monorepo#3321] opened 2023-07-31 13:18 UTC
**Describe the bug**

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**
1. Go to any dapp which supports wallect connect v2 - Here lets take **https://react-app.walletconnect.com/**
2. Try selecting cosmos Hub in mainner
3. Create a connection and do a disconnection from dapp -> The disconnection event is triggered from the Dapp WS console, but not triggered in web3Wallet debug log.
4. If we manually delete the session and delete the pairing topic the event would get triggered from the web3Wallet debug console and also received in dApp WS console.

**Expected behavior**
Proper event session_delete event to be delete in web3Wallet client once the dapp disconnects the wallet from its UI

**Screenshots**

https://github.com/WalletConnect/walletconnect-monorepo/assets/110881421/d78c9242-6bd0-4083-8686-aa8fb9b5a03f

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Android (React native)

**Additional context**
- The Network in which i tested is not under any VPN or such

**Comment by ganchoradkov** [comment] 2023-07-31 14:28
Hey @leapsamvel just tested using a couple of wallets, including https://react-wallet.walletconnect.com and the disconnect seems to be working fine.
Could confirm that you're subscribed to `session_delete` with the wallet you're using in the video?

**Comment by leapsamvel** [comment] 2023-07-31 14:37
Hi @ganchoradkov 
Yes i do have a subscription for it.

There is one more question,

Why, as a wallet, I have to subscribe to the session_delete event, If I am using the getActiveSessions method to show my list of connected dapps?

Any insights @ganchoradkov ?

**Comment by ganchoradkov** [comment] 2023-07-31 14:43
It's helpful so you can update your state when a session is deleted from the other peer and possibly call `getActiveSessions` again to get an updated list of the active sessions. If you're receiving `session_delete`event on the wallet side, then everything works as expected

**Comment by leapsamvel** [comment] 2023-07-31 14:48
Okay.. Just for maintaining the local state correct?

But, here in this video, I am not receiving any event in the web3Wallet log itself. I have loaded web3Wallet library with log level as a trace to see this.

You can see at 0.55-1.00 timeline in this [video](https://drive.google.com/file/d/1LeEU8r1Vwc78s-hYyiIlMtPoewrS1zJc/view?usp=sharing)


And post that you can see many things are going for a toss, even new pairing as well..

**Comment by leapsamvel** [comment] 2023-08-01 06:02
@ganchoradkov  I have logged `getActiveSessions()` output also after disconnection. It is still having the session

https://github.com/WalletConnect/walletconnect-monorepo/assets/110881421/8722a6f9-aa55-485d-b491-ac792e9f342d

**Comment by ganchoradkov** [comment] 2023-08-01 06:35
Could you test if disconnect works when initiated by the wallet? i.e. is the dapp receiving the disconnect?

**Comment by leapsamvel** [comment] 2023-08-01 06:40
I think it does.


https://github.com/WalletConnect/walletconnect-monorepo/assets/110881421/b16be5c8-9ceb-42d6-9088-66464f3efdb5

**Comment by ganchoradkov** [comment] 2023-08-03 07:00
@leapsamvel, could you share minimal repo where we could reproduce the issue? 
Most likely, something is causing the client to unsubscribe from the session topic hence not receiving the payload

**Comment by leapsamvel** [comment] 2023-08-22 15:59
@ganchoradkov 
Trying to setup the repo. will reply back soon

**Comment by leapsamvel** [comment] 2023-08-25 05:56
@ganchoradkov 

https://github.com/leapsamvel/leapwcdemo

Sample Repo



1. Disconnect from dapp is not getting propagated 100% to wallet
2. Get active sessions gives unacknowledged sessions also sometimes 
3. Occasional drop of connection between dapp and wallet results in not showing txn screen sometime / with delay

We are facing these issues with our project. But not seeing with other wallets. 
If possible we can connect in TG and i will share the project Id through the TG group connect with wc team and leap team.

**Comment by barun1313** [comment] 2023-08-26 13:34
Hey @ganchoradkov apologies in the delay in getting back but a lot of the dapps have complained about these issues mentioned above consistently. It would be really helpful if you could escalate this

**Comment by ganchoradkov** [comment] 2023-09-07 08:37
hey @leapsamvel, thanks for the example repo. I checked your `package.json` and saw that you're missing a required package for React Native - `@walletconnect/react-native-compat`
https://docs.walletconnect.com/2.0/web3wallet/about?platform=react-native
It provides needed polyfills to make the SDK function correctly. 

Could you add this package & test it again? I'm pretty confident your issues were caused because of this missing package.
cc @barun1313

**Comment by leapsamvel** [comment] 2023-09-07 08:41
Let me try and get back @ganchoradkov

**Comment by leapsamvel** [comment] 2023-09-11 06:04
@ganchoradkov  My initial testing didn't give me any improvement :(


https://github.com/WalletConnect/walletconnect-monorepo/assets/110881421/4360c93b-1bd8-4cb9-bb6a-ad58e16df983

**Comment by barun1313** [comment] 2023-11-14 08:32
Hey @ganchoradkov, we are still facing these issues quite often and a lot of dapps have pointed this out : 

1. On approving the session from the wallet, we don't get the acknowledgement from the dapp. This does not work consistently and reliably
2. We do not receive delete session events quite often when we disconnect from the dapp

Can you please look into it on priority?

**Comment by glitch-txs** [comment] 2023-12-11 14:36
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.

**Closed as completed by glitch-txs** 2023-12-11 14:36 UTC
Labels: status: awaiting-response
