### ISSUE TITLE
Module not found: Error: Can't resolve 'react-native' 

### ISSUE THREAD

**Issue by RivetParallel** [WalletConnect/walletconnect-monorepo#2351] opened 2023-05-11 09:46 UTC
**Describe the bug**
Module not found: Error: Can't resolve 'react-native' in "node_modules/@walletconnect/universal-provider/dist" when i build application

**SDK Version (if relevant)**
    "@web3modal/ethereum": "^2.4.1",
    "@web3modal/react": "^2.4.1",
    "react-scripts": "^5.0.1",

**Comment by ValiKTHD** [comment] 2023-05-11 10:04
Was just about to open the same issue.

**Comment by arakelovd** [comment] 2023-05-14 23:06
Duplicate of or related to this issue:

https://github.com/WalletConnect/walletconnect-monorepo/issues/2313

**Comment by bkrem** [comment] 2023-05-15 11:32
Thanks @virtuaone, consolidating discussion into #2313

**Closed as not planned by bkrem** 2023-05-15 11:32 UTC
Labels: type: bug, status: duplicate
