### ISSUE TITLE
Module Warning: Failed to parse source map from @walletconnect

### ISSUE THREAD

**Issue by antonio-ivanovski** [WalletConnect/walletconnect-monorepo#1642] opened 2022-11-15 09:03 UTC
**Describe the bug**
There are bunch of warning/error messages printed when bundling with Webpack. 

**Note**: These are just warnings, the `@walletconnect/*` modules are working as expected 

**SDK Version (if relevant)**
 - @walletconnect/sign-client 2.1.3
 - @walletconnect/qrcode-modal: 1.8.0

**To Reproduce**
- Follow the steps from https://docs.walletconnect.com/2.0/javascript/sign/dapp-usage
- Use latest Webpack v5

**Expected behavior**
No warnings are printed and source map is parsed successfully

**Logs**

```
WARNING in ../../../node_modules/@walletconnect/heartbeat/dist/cjs/types/index.js
Module Warning (from ../../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/user/dev/my-app/node_modules/@walletconnect/heartbeat/src/types/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/user/dev/my-app/node_modules/@walletconnect/heartbeat/src/types/index.ts'
 @ ../../../node_modules/@walletconnect/heartbeat/dist/cjs/index.js 14:13-31
 @ ../../../node_modules/@walletconnect/core/dist/index.es.js 1:68-144 1:25506-25513 1:32544-32551 1:52660-52667 1:54077-54079
 @ ../../../node_modules/@walletconnect/sign-client/dist/index.es.js 1:21-149 1:7249-7251 1:22949-22959 1:23374-23384 1:25290-25291 1:25368-25369 1:27200-27202
 @ ./components/RegisterAddress/RegisterAddress.tsx 18:0-52 77:20-35
 @ ./components/RegisterAddress/index.ts 3:0-52 3:0-52
 @ ./routes/SettingsPage/SettingsCardAccounts.tsx 14:0-71 23:171-191
 @ ./routes/SettingsPage/SettingsPage.tsx 9:0-62 17:398-418
 @ ./routes/SettingsPage/index.ts 3:0-46 3:0-46
 @ ./App.tsx 21:0-53 32:236-248 37:236-248
 @ ./index.tsx 6:0-28 10:90-93
```

All the warning and errors: [failed-parse-source-map.txt](https://github.com/WalletConnect/walletconnect-monorepo/files/10010957/failed-parse-source-map.txt)

**Additional context**

**Comment by melanke** [comment] 2023-02-08 17:22
From what I know, this can be easily fixed by adding "src" on the "files" property of `package.json` of each package of walletconnect-monorepo.
They would become something like this:
```json
 "files": [
    "dist",
    "src"
  ],
  ```

**Comment by 2facedsquid** [comment] 2023-03-08 16:32
> From what I know, this can be easily fixed by adding "src" on the "files" property of `package.json` of each package. They would become something like this:
> 
> ```json
>  "files": [
>     "dist",
>     "src"
>   ],
> ```

Have the same problem could you please describe this a bit more

**Comment by melanke** [comment] 2023-03-09 14:28
> > From what I know, this can be easily fixed by adding "src" on the "files" property of `package.json` of each package. They would become something like this:
> > ```json
> >  "files": [
> >     "dist",
> >     "src"
> >   ],
> > ```
> 
> Have the same problem could you please describe this a bit more

Sorry, what I meant is a change on the walletconnect-monorepo, not on the project using it.
I just edited the message to be more clear.

**Comment by melanke** [comment] 2023-03-14 16:29
This is how to reproduce the error:
- `npx create-react-app my-app`
- `cd my-app`
- `npm i @walletconnect/sign-client @walletconnect/types`
- Do a simple Walletconnect setup, only initializing the client
- Run the project
- It will show up a lot of errors on the log

**Comment by rgb2hsl** [comment] 2023-04-07 13:43
Some for me, using Parcel

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/3310192/230618930-9280cc22-16f8-4f6e-92f0-654ab4b8f442.png">

```
Server running at http://localhost:1234
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/jsonrpc-provider/dist/esm/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/jsonrpc-http-connection/dist/esm/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/logger/dist/cjs/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/window-getters/dist/cjs/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/time/dist/cjs/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/relay-api/dist/esm/index.js".
⚠️  Could not load source file "../../src/provider.ts" in source map of "../node_modules/@walletconnect/jsonrpc-provider/dist/esm/provider.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/legacy-provider/dist/esm/index.js".
⚠️  Could not load source file "../../src/watch.ts" in source map of "../node_modules/@walletconnect/time/dist/cjs/watch.js".
⚠️  Could not load source file "../../src/validators.ts" in source map of "../node_modules/@walletconnect/relay-api/dist/esm/validators.js".
⚠️  Could not load source file "../../src/jsonrpc.ts" in source map of "../node_modules/@walletconnect/relay-api/dist/esm/jsonrpc.js".
⚠️  Could not load source file "../../src/parsers.ts" in source map of "../node_modules/@walletconnect/relay-api/dist/esm/parsers.js".
⚠️  Could not load source file "../../../src/constants/index.ts" in source map of "../node_modules/@walletconnect/time/dist/cjs/constants/index.js".
⚠️  Could not load source file "../../../src/utils/index.ts" in source map of "../node_modules/@walletconnect/time/dist/cjs/utils/index.js".
⚠️  Could not load source file "../../../src/types/index.ts" in source map of "../node_modules/@walletconnect/time/dist/cjs/types/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/window-metadata/dist/cjs/index.js".
⚠️  Could not load source file "../../src/types.ts" in source map of "../node_modules/@walletconnect/relay-api/dist/esm/types.js".
⚠️  Could not load source file "../../src/http.ts" in source map of "../node_modules/@walletconnect/jsonrpc-http-connection/dist/esm/http.js".
⚠️  Could not load source file "../../src/utils.ts" in source map of "../node_modules/@walletconnect/logger/dist/cjs/utils.js".
⚠️  Could not load source file "../../src/constants.ts" in source map of "../node_modules/@walletconnect/logger/dist/cjs/constants.js".
⚠️  Could not load source file "../../src/misc.ts" in source map of "../node_modules/@walletconnect/relay-api/dist/esm/misc.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/index.js".
⚠️  Could not load source file "../../../src/types/watch.ts" in source map of "../node_modules/@walletconnect/time/dist/cjs/types/watch.js".
⚠️  Could not load source file "../../../src/constants/misc.ts" in source map of "../node_modules/@walletconnect/time/dist/cjs/constants/misc.js".
⚠️  Could not load source file "../../../src/constants/time.ts" in source map of "../node_modules/@walletconnect/time/dist/cjs/constants/time.js".
⚠️  Could not load source file "../../src/signer.ts" in source map of "../node_modules/@walletconnect/legacy-provider/dist/esm/signer.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/safe-json/dist/esm/index.js".
⚠️  Could not load source file "../../../src/utils/delay.ts" in source map of "../node_modules/@walletconnect/time/dist/cjs/utils/delay.js".
⚠️  Could not load source file "../../../src/utils/convert.ts" in source map of "../node_modules/@walletconnect/time/dist/cjs/utils/convert.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/jsonrpc-utils/dist/esm/index.js".
⚠️  Could not load source file "../../src/qrcode.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/qrcode.js".
⚠️  Could not load source file "../../src/network.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/network.js".
⚠️  Could not load source file "../../src/socket.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/socket.js".
⚠️  Could not load source file "../../src/storage.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/storage.js".
⚠️  Could not load source file "../../src/meta.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/meta.js".
⚠️  Could not load source file "../../src/registry.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/registry.js".
⚠️  Could not load source file "../../src/encoding.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/encoding.js".
⚠️  Could not load source file "../../src/crypto.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/crypto.js".
⚠️  Could not load source file "../../src/events.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/events.js".
⚠️  Could not load source file "../../src/ethereum.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/ethereum.js".
⚠️  Could not load source file "../../src/url.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/url.js".
⚠️  Could not load source file "../../src/misc.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/misc.js".
⚠️  Could not load source file "../../src/window.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/window.js".
⚠️  Could not load source file "../../src/local.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/local.js".
⚠️  Could not load source file "../../src/mobile.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/mobile.js".
⚠️  Could not load source file "../../src/env.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/env.js".
⚠️  Could not load source file "../../src/json.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/json.js".
⚠️  Could not load source file "../../src/protocol.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/protocol.js".
⚠️  Could not load source file "../../src/jsonrpc.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/jsonrpc.js".
⚠️  Could not load source file "../../src/registry.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/registry.js".
⚠️  Could not load source file "../../src/payload.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/payload.js".
⚠️  Could not load source file "../../../src/browser/index.ts" in source map of "../node_modules/@walletconnect/keyvaluestorage/dist/cjs/browser/index.js".
⚠️  Could not load source file "../../src/url.ts" in source map of "../node_modules/@walletconnect/jsonrpc-utils/dist/esm/url.js".
⚠️  Could not load source file "../../src/constants.ts" in source map of "../node_modules/@walletconnect/jsonrpc-utils/dist/esm/constants.js".
⚠️  Could not load source file "../../src/format.ts" in source map of "../node_modules/@walletconnect/jsonrpc-utils/dist/esm/format.js".
⚠️  Could not load source file "../../src/validators.ts" in source map of "../node_modules/@walletconnect/jsonrpc-utils/dist/esm/validators.js".
⚠️  Could not load source file "../../src/session.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/session.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/legacy-client/dist/esm/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/events/dist/esm/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/jsonrpc-types/dist/esm/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/relay-auth/dist/esm/index.js".
⚠️  Could not load source file "../../src/error.ts" in source map of "../node_modules/@walletconnect/jsonrpc-utils/dist/esm/error.js".
⚠️  Could not load source file "../../src/env.ts" in source map of "../node_modules/@walletconnect/jsonrpc-utils/dist/esm/env.js".
⚠️  Could not load source file "../../src/core.ts" in source map of "../node_modules/@walletconnect/legacy-client/dist/esm/core.js".
⚠️  Could not load source file "../../src/utils.ts" in source map of "../node_modules/@walletconnect/relay-auth/dist/esm/utils.js".
⚠️  Could not load source file "../../src/constants.ts" in source map of "../node_modules/@walletconnect/relay-auth/dist/esm/constants.js".
⚠️  Could not load source file "../../src/api.ts" in source map of "../node_modules/@walletconnect/relay-auth/dist/esm/api.js".
⚠️  Could not load source file "../../src/types.ts" in source map of "../node_modules/@walletconnect/relay-auth/dist/esm/types.js".
⚠️  Could not load source file "../../src/misc.ts" in source map of "../node_modules/@walletconnect/jsonrpc-types/dist/esm/misc.js".
⚠️  Could not load source file "../../src/provider.ts" in source map of "../node_modules/@walletconnect/jsonrpc-types/dist/esm/provider.js".
⚠️  Could not load source file "../../src/validator.ts" in source map of "../node_modules/@walletconnect/jsonrpc-types/dist/esm/validator.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/jsonrpc-ws-connection/dist/esm/index.js".
⚠️  Could not load source file "../../../src/constants/index.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/constants/index.js".
⚠️  Could not load source file "../../../src/shared/index.ts" in source map of "../node_modules/@walletconnect/keyvaluestorage/dist/cjs/shared/index.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/environment/dist/cjs/index.js".
⚠️  Could not load source file "../../../src/constants/events.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/constants/events.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/heartbeat/dist/cjs/index.js".
⚠️  Could not load source file "../../../src/shared/types.ts" in source map of "../node_modules/@walletconnect/keyvaluestorage/dist/cjs/shared/types.js".
⚠️  Could not load source file "../../../src/shared/utils.ts" in source map of "../node_modules/@walletconnect/keyvaluestorage/dist/cjs/shared/utils.js".
⚠️  Could not load source file "../../src/jsonrpc.ts" in source map of "../node_modules/@walletconnect/jsonrpc-types/dist/esm/jsonrpc.js".
⚠️  Could not load source file "../../src/crypto.ts" in source map of "../node_modules/@walletconnect/environment/dist/cjs/crypto.js".
⚠️  Could not load source file "../../src/env.ts" in source map of "../node_modules/@walletconnect/environment/dist/cjs/env.js".
⚠️  Could not load source file "../../src/heartbeat.ts" in source map of "../node_modules/@walletconnect/heartbeat/dist/cjs/heartbeat.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/safe-json-utils/dist/cjs/index.js".
⚠️  Could not load source file "../../../src/constants/errors.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/constants/errors.js".
⚠️  Could not load source file "../../../src/constants/jsonrpc.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/constants/jsonrpc.js".
⚠️  Could not load source file "../../../src/constants/mobile.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/constants/mobile.js".
⚠️  Could not load source file "../../src/ws.ts" in source map of "../node_modules/@walletconnect/jsonrpc-ws-connection/dist/esm/ws.js".
⚠️  Could not load source file "../../src/crypto.ts" in source map of "../node_modules/@walletconnect/legacy-client/dist/esm/crypto.js".
⚠️  Could not load source file "../../src/events.ts" in source map of "../node_modules/@walletconnect/events/dist/esm/events.js".
⚠️  Could not load source file "../../../src/constants/networks.ts" in source map of "../node_modules/@walletconnect/legacy-types/dist/esm/constants/networks.js".
⚠️  Could not load source file "../../../src/types/index.ts" in source map of "../node_modules/@walletconnect/heartbeat/dist/cjs/types/index.js".
⚠️  Could not load source file "../../../src/constants/index.ts" in source map of "../node_modules/@walletconnect/heartbeat/dist/cjs/constants/index.js".
⚠️  Could not load source file "../../../src/browser/index.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/browser/index.js".
⚠️  Could not load source file "../../src/events.ts" in source map of "../node_modules/@walletconnect/legacy-client/dist/esm/events.js".
⚠️  Could not load source file "../../src/url.ts" in source map of "../node_modules/@walletconnect/legacy-client/dist/esm/url.js".
⚠️  Could not load source file "../../../src/types/heartbeat.ts" in source map of "../node_modules/@walletconnect/heartbeat/dist/cjs/types/heartbeat.js".
⚠️  Could not load source file "../../../src/constants/heartbeat.ts" in source map of "../node_modules/@walletconnect/heartbeat/dist/cjs/constants/heartbeat.js".
⚠️  Could not load source file "../../src/storage.ts" in source map of "../node_modules/@walletconnect/legacy-client/dist/esm/storage.js".
⚠️  Could not load source file "../../../src/browser/sha2.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/browser/sha2.js".
⚠️  Could not load source file "../../../src/browser/hmac.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/browser/hmac.js".
⚠️  Could not load source file "../../../src/browser/aes.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/browser/aes.js".
⚠️  Could not load source file "../../../src/browser/index.ts" in source map of "../node_modules/@walletconnect/randombytes/dist/esm/browser/index.js".
⚠️  Could not load source file "../../../src/helpers/index.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/helpers/index.js".
⚠️  Could not load source file "../../../src/constants/index.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/constants/index.js".
⚠️  Could not load source file "../../../src/helpers/env.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/helpers/env.js".
⚠️  Could not load source file "../../../src/helpers/types.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/helpers/types.js".
⚠️  Could not load source file "../../../src/helpers/pkcs7.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/helpers/pkcs7.js".
⚠️  Could not load source file "../../../src/helpers/validators.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/helpers/validators.js".
⚠️  Could not load source file "../../../src/constants/length.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/constants/length.js".
⚠️  Could not load source file "../../../src/constants/operations.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/constants/operations.js".
⚠️  Could not load source file "../../../src/lib/browser.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/lib/browser.js".
⚠️  Could not load source file "../../../src/constants/encoding.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/constants/encoding.js".
⚠️  Could not load source file "../../../src/constants/default.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/constants/default.js".
⚠️  Could not load source file "../../src/validators.ts" in source map of "../node_modules/@walletconnect/legacy-utils/dist/esm/validators.js".
⚠️  Could not load source file "../../src/types.ts" in source map of "../node_modules/@walletconnect/jsonrpc-utils/dist/esm/types.js".
⚠️  Could not load source file "../../src/socket.ts" in source map of "../node_modules/@walletconnect/legacy-client/dist/esm/socket.js".
⚠️  Could not load source file "../../src/network.ts" in source map of "../node_modules/@walletconnect/legacy-client/dist/esm/network.js".
⚠️  Could not load source file "../../../src/constants/error.ts" in source map of "../node_modules/@walletconnect/crypto/dist/esm/constants/error.js".
⚠️  Could not load source file "../../src/routing.ts" in source map of "../node_modules/@walletconnect/jsonrpc-utils/dist/esm/routing.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@walletconnect/encoding/dist/esm/index.js".
⚠️  Could not load source file "../../../../src/browser/lib/localStorage.js" in source map of "../node_modules/@walletconnect/keyvaluestorage/dist/cjs/browser/lib/localStorage.js".
```

**Comment by glitch-txs** [comment] 2023-08-08 18:02
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)

**Closed as completed by glitch-txs** 2023-08-08 18:02 UTC
Labels: type: bug

**Comment by thisconnect** [comment] 2023-08-22 15:11
seems to be an issue with latest webpack in react-scripts, more details here https://stackoverflow.com/questions/70996225/wallet-connect-web3-provider-showing-a-lot-of-errors-just-by-imoprting
