### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Beardev118** [WalletConnect/walletconnect-monorepo#3165] opened 2023-07-16 18:54 UTC
**Describe the bug**
Cannot convert undefined or null to object in the Ethereum Provider

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.9.0

**To Reproduce**
            const providerClient = await EthereumProvider.init(providerOptions);
            await providerClient.enable();
            provider = new ethers.providers.Web3Provider(providerClient);
            
           This is working when I load the project in the chrome browser at first
           But logout and try to login again, I got this error
           
           Cannot convert undefined or null to object

**Expected behavior**
 - I think I can get the provider every time

**Comment by ganchoradkov** [comment] 2023-07-17 06:44
Hey @Beardev118 could you provide a reproducible example repo please? 
Which wallet are you testing with?
Could you share the session object?

**Comment by nikoionixx** [comment] 2023-07-19 12:10
I was only facing the same issue .

Downgrade the version to 
 "@walletconnect/ethereum-provider": "2.7.0",

and install additonal pacakage
 "@web3modal/standalone": "^2.4.3",

My Pcakages
    "@walletconnect/ethereum-provider": "2.7.0",
    "@walletconnect/modal": "^2.6.0",
    "@walletconnect/universal-provider": "^2.9.0",
    "@web3modal/standalone": "^2.4.3",

**Comment by Beardev118** [comment] 2023-07-19 12:29
Thank you, let me check

**Comment by davidsx** [comment] 2023-07-20 10:57
Facing the same issue.

**Comment by davidsx** [comment] 2023-07-21 03:42
I started a new project and get my ethereum provider connected properly without any issue with this packages
"@walletconnect/ethereum-provider": "2.9.0",
"@walletconnect/modal": "^2.6.0",

When I return to my original project, it still gets the same error but I found a clue

Somehow the session object from 2.7.0 and 2.9.0 is different and when I upgrade from 2.7.0 to 2.9.0, this error will appear.
Therefore, the proper solution is to clear all the wc-related session (localstorage mainly) and restart your webapp.

Everything works fine after that.

**Comment by nikoionixx** [comment] 2023-07-25 12:51
@davidsx @Beardev118 is it working for you now , i am still getting the Cannot convert undefined or null to object
    at Function.getPrototypeOf error on opening the wallet connect.

**Comment by glitch-txs** [comment] 2023-08-10 01:59
does this happen on prod or dev env? have you tried clearing localStorage?

**Comment by vitoff34** [comment] 2023-08-24 05:34
Clearing localStorage fixed the issue for me.

**Comment by basememara** [comment] 2023-08-31 05:37
I get the same thing but with web3wallet and can't expect users to clear localStorage

**Comment by glitch-txs** [comment] 2023-08-31 08:38
@basememara does this happen on production for you?

**Comment by nikoionixx** [comment] 2023-08-31 09:15
I am using wagmi and WalletConnectConnector , its working fine for me now.

**Comment by josephgathumbi** [comment] 2023-09-14 08:51
I faced the same problem in local dev. My app was working properly but it started throwing the error after I changed the chain Id in the initialization object at the required chains array. 
```
const provider = await EthereumProvider.init({
        projectId: "PROJECT_ID", 
        chains: [1], //changed chain id here
       ...
```
I'm using 
```
"@walletconnect/ethereum-provider": "^2.10.1",
 "@walletconnect/modal": "^2.6.2", 
```
Reverting back to the original chain Id did not solve the issue.

Clearing the local storage as suggested above removed the issue, but I would love to know if there is a permanent fix for users

**Comment by ganchoradkov** [comment] 2023-09-14 09:18
@joseph-gits could you provide a small demo where we could reproduce the issue?

**Comment by glitch-txs** [comment] 2023-12-11 14:37
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.

**Closed as completed by glitch-txs** 2023-12-11 14:37 UTC
Labels: type: bug

**Comment by 0xernesto** [comment] 2024-08-08 17:27
I was getting this issue because I was trying to load the walletConnect projectId as an environment variable, and it was undefined.

For anyone else that runs into this issue, make sure the projectId is not undefined.
