### ISSUE TITLE
IOS 15: iOS Websocket changes break websocket functionality

### ISSUE THREAD

**Issue by wongtszchiu** [WalletConnect/walletconnect-monorepo#1023] opened 2022-05-06 09:16 UTC
**Describe the bug**
When using the ios devices Safari to connect dapp by walletconnect, walletconnect will deeplink you to the wallet app, then the walletconnect websocket will stop (NSURLSession WebSocket). After approve in wallet app, the dapp walletconnect website still waiting connection.

**To Reproduce**
1. Open to 'Safari'
2. Go to 'https://example.walletconnect.org/'
3. Click 'Connect to WalletConnect'
4. Click 'imToken', then deeplink to wallet app
5. Wait few second ( websocket will stoped )
6. Click approve
7. Go back  'https://example.walletconnect.org/'

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: IOS 15

**Additional context**
[https://github.com/react-native-webview/react-native-webview/issues/2281](https://github.com/react-native-webview/react-native-webview/issues/2281)
[https://support.perawallet.app/en/article/resolving-walletconnect-issues-1tolptm/](https://support.perawallet.app/en/article/resolving-walletconnect-issues-1tolptm/)
[https://help.coolwallet.io/article/705-en-walletconnect-on-iphone-keep-crushing-iphone-ios-15-1-120](https://help.coolwallet.io/article/705-en-walletconnect-on-iphone-keep-crushing-iphone-ios-15-1-120)

https://user-images.githubusercontent.com/34164153/167103604-80464500-3446-48a1-a928-165879463481.mp4

**Comment by un7c0rn** [comment] 2022-05-09 16:48
+1. This happens in both Safari and Chrome on iOS 15.4.1. WalletConnect works flawlessly on iOS 14.7.1.

**Comment by wongtszchiu** [comment] 2022-05-10 01:36
> +1. This happens in both Safari and Chrome on iOS 15.4.1. WalletConnect works flawlessly on iOS 14.7.1.

Yes, because IOS 15 use NSURLSession WebSocket.

**Comment by un7c0rn** [comment] 2022-05-10 01:39
@wongtszchiu actually, interesting update. clearing the browser data fixed this for me when I realized two different iOS devices with the same iOS version (15.4.1) had different behavior independent of the NSURLSession WebSocket setting. there's some persistent WC data in localStorage on dev devices that you may need to clear here.

**Comment by wongtszchiu** [comment] 2022-05-10 01:49
> @wongtszchiu actually, interesting update. clearing the browser data fixed this for me when I realized two different iOS devices with the same iOS version (15.4.1) had different behavior independent of the NSURLSession WebSocket setting. there's some persistent WC data in localStorage on dev devices that you may need to clear here.

When I disable the NSURLSession WebSocket in Safari, it will work perfectly. But it is hard to ask all the user to disable it.
https://help.coolwallet.io/article/705-en-walletconnect-on-iphone-keep-crushing-iphone-ios-15-1-120

**Comment by un7c0rn** [comment] 2022-05-10 02:25
@wongtszchiu I have NSURLSession Websocket _enabled_. Do you see this issue in Chrome on iOS 15.4.1?

**Comment by wongtszchiu** [comment] 2022-05-10 02:30
> @wongtszchiu I have NSURLSession Websocket _enabled_. Do you see this issue in Chrome on iOS 15.4.1?

Yes, both Safari and Chrome on iOS 15.4.1 have the same issue.

**Comment by un7c0rn** [comment] 2022-05-10 02:48
> > @wongtszchiu I have NSURLSession Websocket _enabled_. Do you see this issue in Chrome on iOS 15.4.1?
> 
> Yes, both Safari and Chrome on iOS 15.4.1 have the same issue.

After clearing all browsing data?

**Comment by wongtszchiu** [comment] 2022-05-10 02:49
> > > @wongtszchiu I have NSURLSession Websocket _enabled_. Do you see this issue in Chrome on iOS 15.4.1?
> > 
> > 
> > Yes, both Safari and Chrome on iOS 15.4.1 have the same issue.
> 
> After clearing all browsing data?

Yes

**Comment by wongtszchiu** [comment] 2022-05-12 03:04
> > > @wongtszchiu I have NSURLSession Websocket _enabled_. Do you see this issue in Chrome on iOS 15.4.1?
> > 
> > 
> > Yes, both Safari and Chrome on iOS 15.4.1 have the same issue.
> 
> After clearing all browsing data?

I found that MetaMask work perfectly, but dont know how to do it.

**Comment by Kelier** [comment] 2022-08-22 03:20
still issue

**Comment by ElKornacio** [comment] 2022-12-14 16:45
This is still actual. It really makes a lot of pain for us.

WalletConnect can fix it on their side - just by replaying lost messages after the socket reconnects.
Is it possible to implement suck behaviour?

**Comment by elcaptain54** [comment] 2023-05-20 16:45
Also would love to have that fixed or a workaround that doesn't require asking the user to disable the NURLSession setting.

**Comment by grootgordon** [comment] 2023-07-03 10:32
Any way about close NSURLSession  in application self without ask users to setting safari close it?

**Comment by glitch-txs** [comment] 2023-08-08 17:51
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)

**Closed as completed by glitch-txs** 2023-08-08 17:51 UTC
Labels: type: bug

**Comment by mighty-phoenix** [comment] 2023-08-13 20:28
Hey. Im still facing this issue. @glitch-txs 
Any updates on this?
Thanks!

**Comment by glitch-txs** [comment] 2023-08-13 20:32
@mighty-phoenix v1 has been shut down, please update to v2. If you're still facing an issue in the latest version please open a GitHub discussion 🙏

**Comment by mighty-phoenix** [comment] 2023-08-13 21:04
@glitch-txs yes, I'm facing the same issue in v2...

**Comment by mighty-phoenix** [comment] 2023-08-13 21:22
I'm still facing this error in iOS 16 and 17 beta. And when I disable the NSLURLSessions, the connection is instant!
Please help.
Quick response would be highly appreciated.
Thanks! @glitch-txs

**Comment by glitch-txs** [comment] 2023-08-13 21:24
@mighty-phoenix can you open a new issue with a minimal reproducible example and your packages versions?

**Comment by mighty-phoenix** [comment] 2023-08-13 21:27
Sure.
Thanks! @glitch-txs

**Comment by alexanderkhitev** [comment] 2023-09-05 13:38
Hey guys! Any updates? Thanks!

**Comment by glitch-txs** [comment] 2023-09-05 13:41
hey @alexanderkhitev could you provide a [MRE](https://github.com/orgs/WalletConnect/discussions/3457)?
