### ISSUE TITLE
@walletconnect/web3-provider sends so much eth_getBlockByNumber requests

### ISSUE THREAD

**Issue by vwpo** [WalletConnect/walletconnect-monorepo#357] opened 2020-09-21 20:38 UTC
I'm using `@walletconnect/web3-provider@1.2.2` and have some issues with infura's rate limitation. In 'network' tab I can see some crazy amount of `eth_getBlockByNumber` requests. Delay between requests is only 1s (!!!) and of course I'm having some troubles with limitations on infura.

Also I was trying to connect wallet through rpc by providing url to my node. And it works perfectly (only one `eth_getBlockByNumber` request in 30s)

packages:
`web3@1.2.6`
`@walletconnect/web3-provider@1.2.2`

**Comment by garyng2000** [comment] 2021-01-27 16:47
anyone progress on this ? using 1.3.4 and the frequent polling of infura is definitely there. What was the intend for this polling ?

**Comment by sudoryan** [comment] 2021-03-01 22:33
My team is also having issues with these call as they are taking a significant chunk out of our Infura rate limit

**Comment by pedrouid** [comment] 2021-03-03 11:59
Agreed. We are using web3-provider-engine which includes a polling subprovider which used to be required for legacy version of web3.js

We are working on completely deprecating this dependency all together

However you can fix this issue right now by passing an option called `pollingInterval` which can be set for a very high number to reduce the amount of requests

**EDIT:** also noticed you are using 1.2.2 which I believe had a much lower pollingInterval by default

**Comment by miohtama** [comment] 2021-05-05 07:12
Note that this is web3.js issue, not WalletConnect issue.

Some documentation here:

https://web3js.readthedocs.io/en/v1.3.4/web3-eth.html?highlight=transactionPollingTimeout#transactionpollingtimeout

My recommendation is to use WebSockecks, because due to push it does not need to pull, or use OpenZeppelin, ethers.js instead of web3.js.

**Comment by garyng2000** [comment] 2021-05-05 07:24
you mean once I create web3, it starts polling ? don't seem to see this behavior if I connect to metamask plugin of the browser

**Comment by miohtama** [comment] 2021-05-07 09:42
Because MetMask uses WebSockets connection, not HTTPS connection.

**Comment by horodnicdragos** [comment] 2021-12-10 15:45
Hi there! Any updates on this? 

I'm using `@walletconnect/web3-provider 1.6.2` and `pollinInterval` is completely ignored. It's sending one request per second which quickly throttles users rendering them unable to use the app through walletconnect.

**Comment by timraybould** [comment] 2021-12-12 03:29
If you don't need to keep a listener active, you can call `disconnect()` [[docs](https://docs.walletconnect.com/1.0/quick-start/dapps/web3-provider#provider-methods)]. For example:

    import WalletConnectProvider from "@walletconnect/web3-provider"

    const provider = new WalletConnectProvider({
      infuraId: "xxxxxxxxx",
    })

    await provider.enable()
    //do your stuff
    await provider.disconnect()

**Comment by horodnicdragos** [comment] 2021-12-14 08:57
Thank you for your suggestion! While this might work for certain scenarios I do need to have balance and block number in sync so it's not a viable option. However 1s is too low, something like 15-30s would be ideal.

I'm trying to understand exactly why `pollingInterval` is completely ignored as that would by far be the right fix in my case. If it's supposed to work should I open a separate issue with code that reproduces this behavior?

**Comment by atkeson** [comment] 2021-12-26 02:50
Bump! Also having this issue and its eating through my infura limit. Had to upgrade. My workaround was to clone and manually change to 15 seconds but that seems silly and hard to keep updated as things change. Also just supporting web-sockets (AFAIK there is not support at the moment) would be huge.

**Comment by derivativedegen** [comment] 2022-02-03 16:49
Bump again! There really needs to be a way to supply the pollingInterval instead of having to go into the module itself and manually change it. Reverts back to default every time dependencies are updated or installed.

**Comment by zhongyangfu** [comment] 2022-02-08 15:20
Same here. Really frustrating to deal with this.

**Comment by TristonH55** [comment] 2022-03-11 01:35
I am also getting this same issue and tried adding this https://gyazo.com/d68e2413b8fd38dfb559527d5f306a6a to the config file but its still making 1000s of requests. anyone have a fix for this ?

**Comment by pasevin** [comment] 2022-07-13 06:09
Still a huge issue. Any progress on this?

**Comment by pasevin** [comment] 2022-07-13 12:56
Looks like the latest https://www.npmjs.com/package/@walletconnect/web3-provider/v/1.8.0-rc.0 fixed it? We are not experiencing the limit anymore.

**Comment by kris-w-stkd** [comment] 2022-08-09 06:07
I just updated to 1.8.0-rc.0 and still get too much infura spam from walletconnect (created via onboard). Can this polling param be overridden after instantiation?

**Comment by faizyboy1** [comment] 2022-08-31 10:25
Same this is causing so much problem. I know why this is happening `"@walletconnect/web3-provider": "^1.8.0-rc.0"` using [web3-provider-engine](https://github.com/MetaMask/web3-provider-engine) package, which is using an older version of 
`eth-block-tracker` package. However, `eth-block-tracker` no longer support web3-provider-engine, and it seems that WalletConnect doesn't support @walletconnect/web3-provider.

**Comment by varseb** [comment] 2022-10-14 15:57
You can do `provider.disconnect()` as mentioned above, this will end the bridge session after doing your stuff.

If you need the connection remains active and you are not listening to any blockchain event, you can call `provider.stop()` this will stop the blockTracker polling, you will be not able to do `tx.wait()` but methods like `personal_sign` or `estimate_gas` will continue working

provider events like `accountsChanged` and `chainChanged` will work as well

**Comment by finessevanes** [comment] 2022-12-01 04:47
I see a few bumps in here. A few of you seem to have gotten your issue resolved, but I wanted to see if anyone else was still experiencing this issue. cc: @kris-w-stkd, @pasevin, @TristonH55, @derivativedegen, @horodnicdragos, @vwpo

**Closed as not planned** 2023-01-10 01:15 UTC
Labels: status: needs information, protocol-version: v1
