### ISSUE TITLE
The `connect` function from `UniversalProvider` throws error

### ISSUE THREAD

**Issue by bonnopc** [WalletConnect/walletconnect-monorepo#4167] opened 2024-01-23 17:49 UTC
Hey, I am using the `@walletconnect/universal-provider@2.11.0`, `@web3modal/standalone@2.4.3` & `ethers@5.7.2` for my project. Recently I upgraded the universal provider from `v2.3.2` to `v2.11.0` and `@web3modal/standalone` from `v2.1.1` to `v2.4.3`. After that, I am getting the following error while using the `connect` function of the provider. Here's an example code of how I'm using it:

```js
const universalProvider = await UniversalProvider.init({
    projectId: WALLETCONNECT_PROJECT_ID,
    metadata: {
        name: "AppName",
        description: "...",
        url: "https://xxxxx.com",
        icons: [APP_LOGO_URL ?? ""],
    },
});

try {
    await universalProvider.connect({
        namespaces: {
            eip155: {
                methods: [
                    "eth_sendTransaction",
                    "eth_signTransaction",
                    "eth_sign",
                    "personal_sign",
                    "eth_signTypedData",
                    "wallet_switchEthereumChain",
                ],
                chains: ALLOWED_CHAIN_IDS.map(c => `eip155:${c}`),
                events: ["chainChanged", "accountsChanged"],
                rpcMap: RPC_URLS,
            },
        },
    });
} catch(e) {
     console.error("Error on wcProvider.connect: ", e);
}
```
Following is the error I'm getting:
```
Cannot read properties of undefined (reading 'getDefaultChain')
```

**SDK Version (if relevant)**
 - Client: Next.js - v13.1.6
 - `@walletconnect/universal-provider` - v2.11.0
 - `@web3modal/standalone` - v2.4.3
 - `ethers` - v5.7.2

**To Reproduce**
Please follow the code snippet mentioned above and try to scan the QR code. After it gets scanned the error pops up.

**Expected behavior**
It should connect to the wallet

**Screenshots**
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/21574188/219b8416-4f53-451c-aaa9-55d31d4c2af6)

**Device Info:**
 - OS: MacOS
 - Browser: Chrome 
 - Version: 120.0.6099.234 (Official Build) (arm64)

**Additional context**
This doesn't show up for every wallet. For example - I found the error for the Fireblock wallet but, works as expected for the Zerion wallet.

**Comment by meeh0w** [comment] 2024-01-24 13:34
I think Fireblocks stopped supporting `wallet_switchEthereumChain` method. We noticed the same thing for Fireblocks and removing this requirement from the session proposal worked. Try removing it from your session proposal and see if this helps. 

I know it's not really a solution, though ¯\\\_(ツ)_/¯

**Comment by bonnopc** [comment] 2024-01-24 14:07
@meeh0w Thanks for the suggestion. I will definitely try this approach. Currently, I am using the `wallet_switchEthereumChain` method to switch between chains. Should I use the `provider.setDefaultChain` method instead?

**Comment by meeh0w** [comment] 2024-01-24 14:21
I'm not sure what `provider.setDefaultChain` does under the hood, but my guess would be that it's probably using `wallet_switchEthereumChain` too, in which case this wouldn't change anything.

**Comment by meeh0w** [comment] 2024-01-24 17:27
@bonnopc I have contacted Fireblocks support team and apparently they're working on a fix. Very likely it will resolve your issue as well.

**Comment by bonnopc** [comment] 2024-02-05 17:52
> I think Fireblocks stopped supporting `wallet_switchEthereumChain` method. We noticed the same thing for Fireblocks and removing this requirement from the session proposal worked. Try removing it from your session proposal and see if this helps.
> 
> I know it's not really a solution, though ¯\_(ツ)_/¯

@meeh0w Thanks, it worked. But I hope they continue to support `wallet_switchEthereumChain` method.

**Comment by ganchoradkov** [comment] 2024-02-06 15:36
Hey, the issue is resolved and released with https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.11.1

**Closed as completed by ganchoradkov** 2024-02-06 15:36 UTC
Labels: type: bug
