### ISSUE TITLE
No matching key. keychain: e0f87ca5e36729e59fd8b58bcd0acf188262d1440add2af32560d47df5f0e0c6

### ISSUE THREAD

**Issue by Jlp18** [WalletConnect/walletconnect-monorepo#4084] opened 2023-12-26 11:26 UTC
**Describe the bug**
When I scan the QR code and connect successfully, sometimes it will appear in the console when I send a transaction.

**SDK Version (if relevant)**
 - @walletconnect/ethereum-provider": "^2.10.1

**To Reproduce**
1. After the connection is maintained for a period of time, when send a transaction, and it will appear occasionally.

**Screenshots**
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/32257090/55b25368-d666-456a-99f7-7442fecdf566)

**Comment by glitch-txs** [comment] 2024-07-06 01:41
closing as duplicate of https://github.com/WalletConnect/walletconnect-monorepo/issues/4122

Please upgrade to the latest version of WalletConnect.

**Closed as completed by glitch-txs** 2024-07-06 01:41 UTC
Labels: type: bug
