### ISSUE TITLE
Module not found: Error: Can't resolve 'react-native'

### ISSUE THREAD

**Issue by mr-new-0509** [WalletConnect/walletconnect-monorepo#2361] opened 2023-05-12 09:33 UTC
Hello, ladies and gentlemen. :D

This is the source.
https://github.com/mr-new-0509/scotty-the-ai-swap

I tried to build the project but faced this error.
`Module not found: Error: Can't resolve 'react-native' in 'D:\...\scotty-the-ai-swap\node_modules\@walletconnect\universal-provider\dist'`

Could you let me know how to fix this?

Thank you.

**Comment by bkrem** [comment] 2023-05-12 09:39
Duplicate of #2351

**Closed by bkrem** 2023-05-12 09:39 UTC
Labels: type: bug
