### ISSUE TITLE
How to log in to stellarx

### ISSUE THREAD

**Issue by gityms123** [WalletConnect/walletconnect-monorepo#1168] opened 2022-06-18 06:56 UTC
### Discussed in https://github.com/WalletConnect/walletconnect-monorepo/discussions/1101

<div type='discussions-op-text'>

<sup>Originally posted by **gityms123** May 30, 2022</sup>
I found on the official website [](https://walletconnect.com/registry?type=dapp&version=2) that stellarx supports V2, but the QR code for stellarx login is like this,**wc:5f1cb4c0a60ad299993344903d33feaa9bc2b3f80900f826f5a4fd01137fb66c@2?controller=false&publicKey=3b250075ba24f1a0131fdcb75d88d29dabe009b3f75ca9a03227f786b1a22135&relay=%7B%22protocol%22%3A%22waku%22%7D**
Even the validateWCUri method fails to pass</div>

**Comment by chadyj** [comment] 2022-06-18 07:06
Closing.
Dupe of the discussions.

**Closed as completed by chadyj** 2022-06-18 07:06 UTC
