### ISSUE TITLE
console log error upon Web3Wallet.init 

### ISSUE THREAD

**Issue by SamerZen** [WalletConnect/walletconnect-monorepo#3283] opened 2023-07-26 14:06 UTC
**Describe the bug**
Getting console log errors regarding unhandled promise rejection when initializing the Web3Wallet. 

**SDK Version (if relevant)**
 - Client: JS - @walletconnect/web3wallet 
 - Version 1.8.7
 - react-native

**To Reproduce**

 initialize client with minimum config

      const core = new Core({
          projectId: 'PROJECT_ID"
      });
      
      web3Client = await Web3Wallet.init({
        core,
        metadata,
      })

**Screenshots**
<img width="840" alt="Screenshot 2023-07-26 at 10 43 20" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/122724019/5407f375-86cd-44cc-92ea-6830acb741b6">

**Comment by ganchoradkov** [comment] 2023-07-26 14:09
Hey, `createExpiringPromise` should come from `@walletconnect/utils`, please check if you have this package declared with an outdated version in your `package.json`

**Comment by SamerZen** [comment] 2023-07-26 15:11
Hello, 
I am on @walletconnect/utils version 2.9.1, also @walletconnect/react-native-compat 2.9.1
:)

**Comment by ganchoradkov** [comment] 2023-07-27 05:33
Could you provide an example repo where we can reproduce the issue?
We have several examples running Web3Wallet SDK just fine so I would assume the issue is related to your projects bundler
https://github.com/WalletConnect/web-examples/tree/main/wallets/react-web3wallet

**Comment by glitch-txs** [comment] 2023-12-11 14:37
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.

**Closed as completed by glitch-txs** 2023-12-11 14:37 UTC
Labels: status: awaiting-response
