### ISSUE TITLE
Websocket disconnect when debug web page on mobile device

### ISSUE THREAD

**Issue by Santiago0412** [WalletConnect/walletconnect-monorepo#1465] opened 2022-09-22 06:33 UTC
**Describe the bug**
Get an error when try to debug the behavior of my dapp when connect wallet from mobile device.
[Error] WebSocket connection to 'ws://192.168.2.129:4000/_next/webpack-hmr' failed: WebSocket is closed before the connection is established.
	handleDisconnect (websocket.js:53)
And WalletConnect can't activate meta mask.

**SDK Version (if relevant)**
 - Client: JS
 - Version: Latest

**To Reproduce**
1.start my server on my computer;
2.paste the ipaddress+localpath on my mobile browser and launch my dapp;
3.click connect button on my dapp and try to connect to my wallet(metamask);
4.page error and nothing happened(get error: _WebSocket connection to 'ws://192.168.2.129:4000/_next/webpack-hmr' failed: WebSocket is closed before the connection is established._ from console);

**Expected behavior**
web socket works fine and my dapp on mobile can open metamask rightly.

**Comment by finessevanes** [comment] 2023-03-28 03:55
@Santiago0412 1. is this still an issue, if so, what SDK version are you using?

**Comment by bkrem** [comment] 2023-04-11 15:03
Closing.

This seems to be a websocket issue with webpack/hot reloading (`[Error] WebSocket connection to 'ws://192.168.2.129:4000/_next/webpack-hmr' failed`) and not with any websocket WalletConnect establishes.

If this is for the v2 Sign SDK/web3Wallet SDK, metamask won't connect because they haven't shipped v2 support yet. Please provide a reproduction using a [wallet that support Sign v2](https://explorer.walletconnect.com/?version=2) and we can reopen.

**Closed as completed by bkrem** 2023-04-11 15:03 UTC
Labels: type: bug, status: needs information
