### ISSUE TITLE
Can't add URL in Homepage section

### ISSUE THREAD

**Issue by e-nzo27** [WalletConnect/walletconnect-monorepo#3716] opened 2023-09-27 07:24 UTC
Hi, trying to update  app credentials here https://cloud.walletconnect.com/app. Can't add URL in Homepage section – constant error "new row violates row-level security policy for table "registry_submission" (even if I keep there the current url)

**Comment by Cali93** [comment] 2023-09-27 07:44
Hi @e-nzo27, 
We couldn't reproduce the issue but we will investigate further. 
Could you provide your project ID ?  Did you take any other action before trying to update the home page?

**Comment by e-nzo27** [comment] 2023-09-27 09:55
Hi, ID 4fe340f51c26d1d6856fc7c3d84ff0f4
No, haven't taken any other actions

**Comment by e-nzo27** [comment] 2023-09-28 08:40
@Cali93 could you update the Homepage url please? https://stasis.net/wallet -> https://stasis.net

**Comment by Cali93** [comment] 2023-09-28 09:05
Hi @e-nzo27, we just found the issue and are working on a fix.
We will let you know as soon as it's fixed and you'll be able to update it yourself.

**Comment by Cali93** [comment] 2023-09-28 14:01
Hey @e-nzo27, the issue has been fixed in the latest release.
Let us know if you're facing any issue.

**Closed as completed by Cali93** 2023-09-28 14:01 UTC
