### ISSUE TITLE
Redirect from website to wallet and wallet to website is broken

### ISSUE THREAD

**Issue by doomhz** [WalletConnect/walletconnect-monorepo#1405] opened 2022-09-01 17:40 UTC
**Describe the bug**
The flow of redirecting users from the website QRModal to the crypto wallet and back got broken. Recently, there is a new redirect screen in between on which the user gets stuck, without knowing what to do next. Sometimes, the redirect from the crypto wallet doesn't even work at all.
Sometimes I get `WalletConnect session was disconnected.` error (see screenshots) and sometimes a `chainId` error in my JS browser console.

**SDK Version (if relevant)**
 - Client: [JS]
 - Version [1.7.8+,1.8+]

**To Reproduce**
1. Go to [https://pxhvh5.csb.app/](https://pxhvh5.csb.app/) on your phone.
2. Click on 'Authorize'.
3. Follow the authorisation flow on Trust wallet or MetaMask.
4. Get stuck on the in-between page.

**Expected behavior**
Get redirected back to the website after a successful auth sign from Trust wallet or MetaMask (or any other 3rd party wallet which supports WalletConnect).

**Screenshots**
- [Demo Video 1](https://www.dropbox.com/s/339nmiwkv6x0hwe/walletconnect_issue_1.MP4?dl=0)
- [Demo Video 2](https://www.dropbox.com/s/u8m0jy2dnhdbwwc/walletconnect_issue_2.MP4?dl=0)
- [WalletConnect session was disconnected error](https://www.dropbox.com/s/rt4f1aj7gn1quhq/walletconnect_issue_3.png?dl=0)

**Smartphone (please complete the following information):**
 - Device: [iPhone13]
 - OS: [15.6.1]
 - Browser [safari]
 - Version [15.6]

**Comment by chadyj** [comment] 2022-09-02 15:54
Looks like a duplicate of https://github.com/WalletConnect/walletconnect-monorepo/issues/1165

**Closed as not planned** 2023-02-07 07:29 UTC
Labels: type: bug
