### ISSUE TITLE
1.7.4 - Uncaught Error: User closed modal

### ISSUE THREAD

**Issue by NoahZinsmeister** [WalletConnect/walletconnect-monorepo#839] opened 2022-03-07 21:38 UTC
as reported in https://github.com/NoahZinsmeister/web3-react/issues/454, the `1.7.4` release of `@walletconnect/ethereum-provider` has a regression. when a user closes the qr modal, there's an unhandled `Uncaught Error: User closed modal`

see https://web3-react-lsff62x8m-noahwz.vercel.app/ for a repro

**Comment by NoahZinsmeister** [comment] 2022-03-07 21:39
here's the full stack trace:

```
Unhandled Runtime Error
Error: User closed modal

Call Stack
Object.eval [as callback]
../../node_modules/@walletconnect/signer-connection/dist/esm/index.js (160:0)
eval
../../node_modules/@walletconnect/core/dist/esm/events.js (41:0)
Array.forEach
<anonymous>
EventManager.trigger
../../node_modules/@walletconnect/core/dist/esm/events.js (35:0)
eval
../../node_modules/@walletconnect/core/dist/esm/index.js (759:0)
Object.eval [as click]
../../node_modules/@walletconnect/qrcode-modal/dist/cjs/index.js (614:0)
HTMLDivElement.z
../../node_modules/@walletconnect/qrcode-modal/node_modules/preact/dist/preact.module.js (1:4109)
```

**Comment by NoahZinsmeister** [comment] 2022-03-07 21:43
if you want to repro this locally, there's a branch here: https://github.com/NoahZinsmeister/web3-react/tree/walletconnect-bug-repro

**Comment by welps** [comment] 2022-03-08 02:03
I pinged Noah about this in Slack, but this is not related to 1.7.4.

#747 is the existing report for this 

Here's the issue happening in 1.7.1 just for posterity:
![2022-03-07-205437_1920x345_scrot](https://user-images.githubusercontent.com/677680/157151465-37c170cd-b93c-4af7-bd4c-1dc18236cb6c.png)

**Comment by pedrouid** [comment] 2022-03-14 15:12
Fixed on v1.7.5

**Closed as completed by pedrouid** 2022-03-14 15:12 UTC

**Comment by nichochar** [comment] 2022-05-01 04:34
I am observing this in v1.7.8
<img width="1002" alt="Screen Shot 2022-04-30 at 9 33 47 PM" src="https://user-images.githubusercontent.com/1666947/166132349-00d8cc62-ad43-47c8-9330-7fa24fbe7c8f.png">

**Comment by kkagill** [comment] 2022-05-12 23:25
yes i'm still observing this in 1.7.8 too

**Comment by MuckT** [comment] 2022-05-12 23:33
As a work around you can throw it in a try/catch to handle the user closing the modal without connecting.
```
  const handleWalletConnect = async () => {
    try {
      await connect()
    } catch (e) {
      console.warn(e)
    }
  }
 ```

**Comment by kkagill** [comment] 2022-05-12 23:36
@MuckT thanks, but where do I add that when it's happening from the library?
![image](https://user-images.githubusercontent.com/7738916/168184122-eb646ec8-54cf-4e9e-a6fa-76e2306ab284.png)

**Comment by sa-ma** [comment] 2022-11-17 22:03
> @MuckT thanks, but where do I add that when it's happening from the library? ![image](https://user-images.githubusercontent.com/7738916/168184122-eb646ec8-54cf-4e9e-a6fa-76e2306ab284.png)

@kkagill  were you able to solve this?

**Comment by rafal2228** [comment] 2022-11-29 11:32
@nichochar @kkagill @sa-ma

I know it's a bit late, but I believe I've found the root cause of the issue with V6. There are two things which you probably need to check to resolve this:

Ensure through `yarn list`/`npm ls` that you're using `@walletconnect/ethereum-provider` in version `1.7.5` or above - this is the original fix of this issue for V8

Add custom logic for handling disconnection of walletconnect connector. There's a difference how v6 and v8 handle creation of internal `@walletconnect/ethereum-provider` - in v8 it's always recreated after disconnection and v6 tries to reuse already existing one. The behavior of v6 seems to be incompatible with WC provider. You can see the problem even in official example of v6:

Steps to reproduce:
- open https://codesandbox.io/s/sparkling-cache-rp7x90
- connect your wallet with walletconnect connector
- disconnect your wallet
- open walletconnect modal again
- close it with "X" button
- the internals of walletconnect library throw unhandled "User closed modal" error

The fix for this is quite simple - you can override the `deactivate` function of `useWeb3React` hook to clear this internal provider manually - luckily it's public from TS perspective:

```ts
export const useWallet = () => {
  const { deactivate, connector, ...context } =
    useWeb3React<providers.Web3Provider>();

  const handleDeactivate = useCallback(() => {
    deactivate();

    if (connector instanceof WalletConnectConnector) {
      connector.walletConnectProvider = undefined;
    }
  }, [connector, deactivate]);

  return {
    ...context,
    connector,
    deactivate: handleDeactivate,
  };
};
```

See the updated examples:

- https://codesandbox.io/s/relaxed-rgb-28mcc9?file=/pages/index.tsx - version without clearing LS logic, reconnecting to previously used wallet
- https://codesandbox.io/s/compassionate-albattani-wrcvty - version with LS clear to ensure user gets prompted again with wallet selection modal

If you're persisting the state of WC connection in localstorage it might be also necessary to clear it manually - otherwise WC will reuse previously selected wallet on second modal opening.

@NoahZinsmeister I know v6 is not actively maintained, but maybe this fix for walletconnect connector is something still worth adding there?

**Comment by PaulRBerg** [comment] 2023-01-04 13:17
Am I understanding correctly that in web3-react v8, this bug is no longer present?
