### ISSUE TITLE
How do you connect to other EVM blockchains like Celo

### ISSUE THREAD

**Issue by ohenepee** [WalletConnect/walletconnect-monorepo#1770] opened 2022-12-15 15:29 UTC
### Discussed in https://github.com/orgs/WalletConnect/discussions/1769

<div type='discussions-op-text'>

<sup>Originally posted by **ohenepee** December 15, 2022</sup>
I've spent the last 5 hours searching here and there both on WalletConnect v2 & Web3Modal pages for using custom chains, there's guide on that except [here](https://docs.walletconnect.com/2.0/web3modal/configuration) where it mentions `standaloneChains` with some short text and an example that has literally no meaning for anyone new to WallectConnect or Web3Modal.</div>

**Comment by chadyj** [comment] 2022-12-15 15:47
Dupe of the discussion. Closing.

**Closed as completed** 2022-12-15 16:04 UTC
