### ISSUE TITLE
Refused to frame error on localhost

### ISSUE THREAD

**Issue by christopheSeeka** [WalletConnect/walletconnect-monorepo#4260] opened 2024-02-23 12:37 UTC
Hello,

I'm getting the following error when dev in localhost, i didn't had such issue before.

`Refused to frame 'https://verify.walletconnect.org/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://*.blockai.dev https://blockai.dev".`

or

```
{context: 'core'} {context: 'core/relayer'} Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
```
My understanding was that localhost is automatically whitelisted but it seem not, could it be because i use subdomains like this:
http://tgp.localhost:6230

I tried to add it to Origin allow list on the cloud as http://tgp.localhost:6230 or http://*.localhost:6230
 but still have this error, online it works.

Using following libs versions in vue3:

```
"@walletconnect/client": "^1.8.0",
"@walletconnect/ethereum-provider": "^2.11.2",
"@walletconnect/modal": "^2.6.2",
"@walletconnect/web3-provider": "^1.8.0",
```

**Comment by blankey1337** [comment] 2024-03-03 22:03
+1, also seeing this issue. I'm not using subdomains, just localhost:3000

**Comment by Cali93** [comment] 2024-03-05 14:03
Hey, thanks for reporting this issue. 
We will add a dev mode option on https://cloud.walletconnect.com to let you use Verify API locally.
We will let you know as soon as it's implemented.

**Comment by Apexl2** [comment] 2024-05-06 18:37
Cool! Can't wait for it!

**Comment by rromanovsky** [comment] 2024-05-23 16:29
How to fix it at least for now?
I also have 
`Refused to frame 'https://verify.walletconnect.org/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://*.my.app https://my.app".`

**Comment by sawproduction** [comment] 2024-06-19 13:04
any update on this

**Comment by glitch-txs** [comment] 2024-07-06 11:48
Duplicate of https://github.com/WalletConnect/walletconnect-monorepo/issues/4277

**Closed as completed** 2024-07-06 11:48 UTC
Labels: type: bug, status: WIP, accepted
