### ISSUE TITLE
Send signed transaction from app instead of wallet with Web3

### ISSUE THREAD

**Issue by geigerzaehler** [WalletConnect/walletconnect-monorepo#369] opened 2020-10-07 13:44 UTC
We’re building a frontend for our smart contracts with Web3 and WalletConnect. For development we’re using a local Ethereum node where we can easily deploy our smart contracts. However, this setup is not easily compatible with the WalletConnect Web3 provider.  If we ask web3 to submit a transaction from the frontend, WalletConnect will ask the connected wallet to both sign _and send_ the transaction. The wallet does not have access to the local Ethereum node (or this is cumbersome to configure, say for MetaMask) and will instead send it to the network that is selected on the wallet.

Ideally the Web3 provider could be configured to have the connected wallet just sign the transaction and then return it to the provider in the frontend. The provider would then take care of sending the transaction to the network it is configured for.

**Comment by miohtama** [comment] 2020-12-10 10:48
This is a problem with mobile wallet themselves, as they do not provide configurable network options like desktop MetaMask.

The root cause and the solution for it would be having configurable networks in mobile wallets. I do not think there is a merit to do a hack on WalletConnect, as the issue is with mobile wallet vendors and should be fixed in mobile wallets themselves.

To get the issue fixed, I suggest you start building business relationships with mobile wallet developers. I know that some wallets provide configurable network options in their beta releases, but remove this for production releases distributed in app stores.

**Closed as not planned** 2022-12-06 19:13 UTC
