### ISSUE TITLE
Please add this new chain.

### ISSUE THREAD

**Issue by ArmaghanRaza** [WalletConnect/walletconnect-monorepo#3110] opened 2023-07-12 09:35 UTC
All JSON-RPC methods mentioned in (https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) are present in XANAChain's rpc. For more details (https://docs.avax.network/apis/avalanchego/apis)

GitHub Link: eip:155 for Ethereum/EVM-based chains

namespaces: eip155

chains:
Mainnet
ChainId: 8888
https://chainlist.org/chain/8888

RPC endpoints:
Mainnet
https://mainnet.xana.net/rpc
wss://mainnet.xana.net/ws

coin type**: 60

Additional context
XANAChain is subnet deployed on Avalanche Mainnet.

**Comment by Cali93** [comment] 2023-07-15 07:59
Duplicate of #3108 which already has been accepted.

**Closed as completed by Cali93** 2023-07-15 07:59 UTC
Labels: type: new chain request
