### ISSUE TITLE
[DNS] The verification code on the text file is invalid

### ISSUE THREAD

**Issue by ravisriv** [WalletConnect/walletconnect-monorepo#3676] opened 2023-09-19 21:30 UTC
**Describe the bug**
If a user had previously verified the domain of their project on (cloud.walletconnect.com/sign-in) and they make changes in their profile and try to re-verify their domain, the domain verification will fail with an error "[DNS] The verification code on the text file is invalid".

**SDK Version (if relevant)**
 - Client: Not applicable
 - Version: Walletconnect 2.0
 - Verify software for domain verification

**To Reproduce**
1. Go to a project profile that has a domain that was verified before the verification string key was changed from "wallet-connect-dns-verification" to a hex string.
2. Update the TXT record in the domain with the new verification string that has a hex string instead of "wallet-connect-dns-verification" key. Just copy and paste it in the TXT content record.
3. Click on the "Verify" button below the domain name.

**Expected behavior**
It should display a message that the domain has been successfully verified.

**Screenshots**
For screenshots, please see this link: https://github.com/WalletConnect/walletconnect-monorepo/issues/3662#issue-1899492252
and this link: https://github.com/orgs/WalletConnect/discussions/3343#discussioncomment-7015725

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Latest

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
None

**Comment by Cali93** [comment] 2023-09-19 21:53
Closing as duplicate of https://github.com/WalletConnect/walletconnect-monorepo/issues/3662

**Closed as completed by Cali93** 2023-09-19 21:53 UTC
Labels: type: bug
