### ISSUE TITLE
@walletconnect/web3-provider cannot find the latest block on xDai

### ISSUE THREAD

**Issue by azf20** [WalletConnect/walletconnect-monorepo#382] opened 2020-10-31 13:18 UTC
Walletconnect web3-provider is not able to find the latest block on xDai

Demo app: https://codesandbox.io/s/walletconnect-network-testing-b852b
Instructions:
_Using a WalletConnect compatible wallet which can connect to xDai_ e.g. metamask mobile app or https://test.walletconnect.org/ 
- First connect with any of mainnet / ropsten / rinkeby / goerli / kovan selected in your WalletConnect wallet
- You should be able to sign a message, getBalance and sendTransaction (which sends a 0 value tx to your connected account)
- If you then switch the network to xDai, there is a recurring error as the provider tries to get the latest block at web3-provider-engine/index.js:58. There is also a related onlyOnce.js error.
![image](https://user-images.githubusercontent.com/9612972/97780226-4f485580-1b7b-11eb-9ffd-d41c6f7e56de.png)
- It is possible to sign a message, getBalance and sendTransaction on xDai, but the getLatestBlock error persists

This appears to be a compatibility issue between https://dai.poa.network and web3-provider-engine

**Comment by varasev** [comment] 2020-11-02 15:42
Seems the issue is in [`web3-provider-engine`](https://github.com/MetaMask/web3-provider-engine) package which is used in https://github.com/WalletConnect/walletconnect-monorepo/blob/next/packages/providers/web3-provider/src/index.ts

The `web3-provider-engine` [sends a `skipCache` parameter](https://github.com/MetaMask/web3-provider-engine/blob/c8d9a8e46703ab417aeeeba583694057f38cfdf7/index.js#L172) in `eth_getBlockByNumber` JSON RPC. xDai currently works primarily on OpenEthereum nodes, but OpenEthereum doesn't support that parameter: https://github.com/openethereum/openethereum/issues/11824

Example:

```
curl --data '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[],"skipCache":true}' -H "Content-Type: application/json" -X POST https://dai.poa.network/
```

returns

```
{"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":1}
```

Without the `skipCache` it works fine:

```
curl --data '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' -H "Content-Type: application/json" -X POST https://dai.poa.network/
```

**Comment by varasev** [comment] 2020-11-02 15:55
That should be fixed in the latest `web3-provider-engine v16.0.1`: https://github.com/MetaMask/web3-provider-engine/commit/bd9ff60ecd0a2f2624012e8d680049ccfb6aaed2

**Comment by varasev** [comment] 2020-11-02 16:18
Also, the issue is in this line: https://github.com/MetaMask/web3-provider-engine/blob/c8d9a8e46703ab417aeeeba583694057f38cfdf7/index.js#L30 - it activates the `skipCache` for `eth_blockNumber` request: https://github.com/MetaMask/eth-block-tracker/blob/be1497a4b193a0e8ee8dff31a307fcaf7bbd5e89/src/polling.js#L71-L81

**Comment by azf20** [comment] 2020-11-03 18:13
thanks @varasev! @pedrouid updated web3-provider-engine to the latest (16.0.1), and I pulled the new version of @walletconnect/web3-provider (1.3.2-rc.1), but still seem to be having the same issue - as well as upgrading that package are there any other changes required? Or does the change need to be made on web3-provider-engine itself (per your last comment) - or can we deactivate the skipCache somehow?

**Comment by varasev** [comment] 2020-11-04 11:53
Regarding the issue with `eth_getBlockByNumber`: since the issue [was fixed](https://github.com/MetaMask/web3-provider-engine/commit/bd9ff60ecd0a2f2624012e8d680049ccfb6aaed2) in `subproviders/rpc.js`, now I'm not sure that exactly this subprovider (rpc.js) is used. Probably, the code uses another subprovider where the payload is still not sanitized. This thing should be researched.

Regarding the issue with `eth_blockNumber`, I think it can be solved by setting an explicit `blockTracker` in this line: https://github.com/WalletConnect/walletconnect-monorepo/blob/10f4a6d162094cbdba5cf54638e79f2a08c04013/packages/providers/web3-provider/src/index.ts#L39

Such a tracker should set `setSkipCacheFlag: false` when initializing, like here: https://github.com/MetaMask/web3-provider-engine/blob/c8d9a8e46703ab417aeeeba583694057f38cfdf7/index.js#L27-L30

**Comment by azf20** [comment] 2021-03-22 12:12
@varasev realised I didn't thank you enough, the patch you suggested above is still working 🙏

**Comment by Ahmedelforjani** [comment] 2022-07-15 21:27
is this issue is still up ? and anyone could fix it?

**Closed as completed** 2022-12-12 20:08 UTC
