### ISSUE TITLE
Unable to pair iOS Lobstr with `2.0.0-rc`

### ISSUE THREAD

**Issue by BenRacicot** [WalletConnect/walletconnect-monorepo#1364] opened 2022-08-19 17:43 UTC
**Describe the bug**
When connecting my localhost app and scanning the QR URI with the Lobstr iOS app nothing happens for about 1 minute until (the timeout) errs:

```
wc:09d4...@2?relay-protocol=irn&symKey=0c8a...

context: "client/expirer" ERROR 'No matching key. expirer: topic:09d4...'
```
UPDATE:
There's also another version of this error seen in other scenarios:
```
No matching key. history:
```

**SDK Version (if relevant)**
    "@walletconnect/sign-client": "^2.0.0-rc.3",
    "@walletconnect/qrcode-modal": "^1.8.0",    
    "@walletconnect/utils": "2.0.0-rc.3",    
    "@walletconnect/types": "^2.0.0-rc.3",

**To Reproduce**
1. Run RC-3, init a connection to create a URI (pop the QR modal)
2. Open Lobstr's latest app and scan your app's QR/URI to connect WC
3. Nothing happens in Lobstr
4. Eventually the `No matching key` error shows in the RC-3 app console.

**Expected behavior**
The WC flow happens when the Lobstr app scans the URI

**Desktop**
 - OS: MacOS
 - Browser Chrome / 104
**Smartphone**
 - Device: iphone 12 / iOS 15.6.1
 - Lobstr App: 8.7.0_311

**Additional context**
Perhaps the RCs are not backwards compatible but it seems the URI should be recognized by Lobstr.

**Comment by jmysliv** [comment] 2022-09-19 09:45
hey! I have the same issue. Have you found what's wrong and how it can be fixed?

**Comment by arein** [comment] 2022-09-19 10:50
Apologies for this. We've occasionally seen this in internal benchmarks. @bkrem and I will investigate.

**Comment by BenRacicot** [comment] 2022-09-19 11:45
No worries! We're here to see WC be the best!
I've spoken to other devs about this and it would seem that as various pairings expire we get this error in the console? 
Not sure still but it does persist in RC-3

**Comment by arein** [comment] 2022-09-19 11:53
That's a good hypothesis. We'll chase it down. We also see it internally in our test suite which is probably another issue. We will chase down your hypothesis and update here.

**Comment by arein** [comment] 2022-09-19 18:47
@BenRacicot @jmysliv the issue you're seeing should have been fixed in https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.0.0-rc.3 can you please upgrade? If you still see this after upgrading please reopen the ticket

**Comment by BenRacicot** [comment] 2022-09-19 19:28
Hey @arein , as mentioned I am seeing this in RC-3

**Comment by arein** [comment] 2022-09-19 19:34
@BenRacicot if only i could read...thx

**Comment by arein** [comment] 2022-09-19 19:40
@BenRacicot is there a publicly available dapp I can test this with?

**Comment by jmysliv** [comment] 2022-09-20 10:14
hey @arein, you can test with this one:  https://skyhitz-expo-next-git-feature-wallet-connect-skyhitzio.vercel.app/.
Here's the pull request if you would need more context: https://github.com/skyhitz/skyhitz-expo-next/pull/36.

In my case, it works with the example wallet: https://github.com/WalletConnect/web-examples/tree/main/wallets/react-wallet-v2 (I had to manually add stellar support), but not with Lobstr.

**Comment by bkrem** [comment] 2022-09-20 14:21
Thanks for the additional context @jmysliv, seeing that you got it working with an extended example wallet is already really helpful for us.

We now have a PR open to fix the `expirer` related erroring (#1459), but this is unrelated to the issue at hand regarding pairing with Lobstr, since it was happening in general after 10 mins when the inactive pairing proposal expires.

Regarding the specific issue when interfacing with Lobstr: 

* AFAIK Lobstr integrated v2 early, so is it possible that they're still running on a `2.0.0-beta...` version and not `2.0.0-rc...`? @chadyj do you happen to know what version Lobstr has in prod?
* That would definitely explain why @jmysliv seems to have no issues with the example wallet (which is on `2.0.0-rc...`), but you both report having issues when trying to pair `2.0.0-rc` to iOS prod Lobstr.

> Perhaps the RCs are not backwards compatible

Just making it explicit: they definitely should be (and so far have been as far as we're aware), thus my hunch that Lobstr is running a pre-rc version

**Comment by bkrem** [comment] 2022-09-20 15:58
### Update

* After checking back about what Lobstr is currently running in prod, it seems to be `beta.102` based on our metrics.
* This explains the incompatibility issues, which should hopefully resolve as soon as Lobstr ships a version supporting any `2.0.0-rc` version

**Comment by bkrem** [comment] 2022-09-21 08:50
Closing this for now since there's no action to be taken from our side. 

Let's reopen if necessary once Lobstr updates their Sign v2 dependency and you're still experiencing issues 👍

**Closed as completed by bkrem** 2022-09-21 08:50 UTC
Labels: scope: sign-client, protocol-version: v2, type: compatibility

**Comment by chadyj** [comment] 2022-10-24 10:58
Update: LOBSTR has upgraded to the latest Sign version, so please try the pairing now.

**Comment by jmysliv** [comment] 2022-10-25 14:40
@chadyj it works now, thanks! 🚀

**Comment by BenRacicot** [comment] 2022-12-14 21:56
Hey @bkrem just getting back to trying with Lobstr after their update.

Error code 1006 (and its message) do not exist in the [sign-client error docs](https://docs.walletconnect.com/2.0/specs/clients/sign/error-codes#session-request). 

My WC app (sign-client 2.1.3) pairs and signs transactions on the Stellar network with xBull wallet (sign-client 2.1.1) 

but Lobstr gives me:
```
code: 1006
message: "The Proposal Namespaces are invalid"
```

Perhaps there is a mismatch in the namespace but how would I know which property values to use?
```
chains: "stellar:pubnet"
events: "accountsChanged"
methods: "stellar_signXDR"
```

UPDATE:
Lobstr requires `methods: ['stellar_signAndSubmitXDR']`

**Comment by ganchoradkov** [comment] 2022-12-15 10:39
@BenRacicot I'm seeing you added an update to your post.
Does this mean the issue is solved on your side?

**Comment by ggaabe** [comment] 2023-02-10 03:24
Hey @ganchoradkov, I'm actually seeing this when relying on the universal provider 2.3.2 on the dapp-side and web3wallet packages
